### PR TITLE
FastTag Pickler

### LINKED ISSUE #32: Runtime crash when pickling a FastTypeTag
Maybe it's a bit weird, but I want to serialize a FastTypeTag, so I can do type verification for a type-safe key-value store I hacked together.
Unfortunately, while the pickling seems to work, unpickling causes a runtime error.

## steps

This code:

    import scala.pickling._, Defaults._
    import scala.pickling.binary._

    val ftt = implicitly[FastTypeTag[Int]]
    val pickled = ftt.pickle
    // Crashes in this line.
    val unpickled = pickled.unpickle[FastTypeTag[Int]]

## problem

fails with this runtime error:

    [info]   scala.reflect.internal.MissingRequirementError: class $anon$1 not found.
    [info]   at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
    [info]   at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.ensureClassSymbol(Mirrors.scala:90)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:119)
    [info]   at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:21)
    [info]   at scala.pickling.package$.typeFromString(package.scala:65)
    [info]   at scala.pickling.FastTypeTag$.apply(FastTags.scala:56)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply$mcV$sp(testPersistentMap.scala:29)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply(testPersistentMap.scala:26)
    [info]   at scalatestextra.TestPersistentMap$$anonfun$1.apply(testPersistentMap.scala:26)

### PR DESCRIPTION
**Pull request by jsuereth**
cc> @phaller as his FastTypeTag changes may already include this.

Fixes #32

### CODE REVIEW

File: core/src/test/scala/scala/pickling/pickler/FastTypeTagTest.scala [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package scala.pickling.pickler
+
+import org.scalatest.FunSuite
+import scala.pickling._, Defaults._, json._
```
Comment (eed3si9n) [inline core/src/test/scala/scala/pickling/pickler/FastTypeTagTest.scala:4]: Could you add `static._` here for preventing future breakage?

Comment (jsuereth) [inline core/src/test/scala/scala/pickling/pickler/FastTypeTagTest.scala:4]: It's a good point, but actually we need to test the inverse.  WE need to check that if people use the WillRobinson algorithm (which is the one that handled FastTypeTag) they will still get our staticly-donated picklers.   i.e. if I add `import static._` I might mask a failure case.
