### PR TITLE
stop compiling when pickler fields are empty. Fixes #60, #263

### LINKED ISSUE #60: Pickling Java classes yields empty objects
Hi,
It seems that java classes aren't currently well handled, when attempting to either pickle directly, or say embedded in fields of pure scala classes. 
The examples below compile successfully, and generate pickled representations.

However in each case:
a) unpickling to the specific type, successfully returns an object, however it's incorrectly initialised. (i.e. it's fields don't match those of the original object)

b) unpickling to [Any] fails at runtime.

This is rather unfortunate, since particularly case (a) could lead to hard to detect errors. 
It would be great if you could take a look.

```scala
package picklingtests
import scala.pickling._
import scala.pickling.json._

import org.joda.time.LocalDate

import org.junit._
import org.junit.Assert._

case class X(date: org.joda.time.LocalDate)

class PickleTest {

  @Test def testPickleCaseClassJavaField_Specific = {
    val dt = LocalDate.now().plusDays(3)
    val x = X(dt)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[X]

    assertEquals(x, restored)
  }
  
    @Test def testPickleCaseClassJavaField_Any = {
    val dt = LocalDate.now().plusDays(3)
    val x = X(dt)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[Any]

    assertEquals(x, restored)
  }
  

  @Test def testPickleJavaClass_Any = {
    val x = LocalDate.now().plusDays(3)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[Any]

    assertEquals(x, restored)
  }

  @Test def testPickleJavaClass_Specific = {
    val x = LocalDate.now().plusDays(3)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[LocalDate]

    assertEquals(x, restored)
  }

  @Test def testPickleJavaClass2_Any = {
    val x = new java.awt.Rectangle(1, 2, 3, 4)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[Any]

    assertEquals(x, restored)
  }

  @Test def testPickleJavaClass2_Specific = {
    val x = new java.awt.Rectangle(1, 2, 3, 4)
    val pickled = x.pickle
    println(pickled)
    val restored = pickled.unpickle[java.awt.Rectangle]

    assertEquals(x, restored)
  }

}
```

Output:
```
JSONPickle({
  "tpe": "picklingtests.X",
  "date": {
  
  }
})
JSONPickle({
  "tpe": "picklingtests.X",
  "date": {
  
  }
})
JSONPickle({
  "tpe": "java.awt.Rectangle"
})
JSONPickle({
  "tpe": "org.joda.time.LocalDate"
})
JSONPickle({
  "tpe": "org.joda.time.LocalDate"
})
JSONPickle({
  "tpe": "java.awt.Rectangle"
})

```

```
picklingtests.PickleTest

testPickleCaseClassJavaField_Specific(picklingtests.PickleTest)
java.lang.AssertionError: expected:<X(2013-10-24)> but was:<X(2013-10-21)>


testPickleCaseClassJavaField_Any(picklingtests.PickleTest)
java.util.NoSuchElementException: key not found: x$1
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:58)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:235)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:159)
    at scala.pickling.InterpretedUnpicklerRuntime$$anon$2$$anonfun$fieldVals$1$1.apply(Runtime.scala:174)



testPickleJavaClass2_Specific(picklingtests.PickleTest)
java.lang.AssertionError: expected:<java.awt.Rectangle[x=1,y=2,width=3,height=4]> but was:<java.awt.Rectangle[x=0,y=0,width=0,height=0]>


testPickleJavaClass_Any(picklingtests.PickleTest)
java.util.NoSuchElementException: key not found: x$1
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:58)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:235)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:159)

testPickleJavaClass_Specific(picklingtests.PickleTest)
java.lang.AssertionError: expected:<2013-10-24> but was:<2013-10-21>


testPickleJavaClass2_Any(picklingtests.PickleTest)
java.util.NoSuchElementException: key not found: x$1
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:58)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:235)
    at scala.pickling.json.JSONPickleReader.readField(JSONPickleFormat.scala:159)
    at scala.pickling.InterpretedUnpicklerRuntime$$anon$2$$anonfun$fieldVals$1$1.apply(Runtime.scala:174)



```

### PR DESCRIPTION
**Pull request by eed3si9n**
Current implementation uses `reflectivelyWithoutGetter` to try accessing primary constructor params by name, and is allowed to fail silently. This ends up generating empty objects for Java classes like `java.lang.Byte`.
- This does not attempt reflection unless we have a known param.
- When the list of fields are non-empty, but the pickler generates zero fields, it will raise exception to fail the macro.
## over-promising issue

venn diagram

In the above diagram, I define _over-promising_ to be the region that's _true_ for _`x.pickle` compiles_ but `false` for _Pickler captures all necessary fields._ Here's a case that intersects with _`pkl.unpickle` unpickles..._

``` scala
scala> import scala.pickling._, Defaults._, json._, static._

scala> val r1: java.lang.Byte = 13.toByte
r1: Byte = 13

scala> val r2 = r1.pickle
r2: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "java.lang.Byte"
})

scala> val r3 = r2.unpickle[java.lang.Byte]
r3: Byte = 0
```
## what this changes

``` scala
scala> import scala.pickling._, Defaults._, json._, static._

scala> val r1: java.lang.Byte = 13.toByte
r1: Byte = 13

scala> val r2 = r1.pickle
<console>:20: error: Cannot generate a pickler for Byte. Recompile with -Xlog-implicits for details
       val r2 = r1.pickle
                   ^
```

Instead of going through with an empty JSON, the `Pickler[java.lang.Byte]` would no longer generate since it was not able to generate any _put fields_.

The following will continue to work.

``` scala
scala> import scala.pickling._, Defaults._, json._

scala> class Foo(x0: Int) { val x = x0 }
defined class Foo

scala> new Foo(1).pickle
res0: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "Foo",
  "x": 1
})
```

### CODE REVIEW

File: core/src/main/scala/pickling/Macros.scala [hunk 1]
```diff
@@ -188,7 +191,8 @@ trait PicklerMacros extends Macro with PickleMacros with FastTypeTagMacros {
               scala.pickling.PickleOps(out).pickleInto(b)
             )
           """)
-        } else (nonLoopyFields ++ loopyFields).flatMap(fir => {
+        }
+        else (nonLoopyFields ++ loopyFields).flatMap(fir => {
```
Comment (havocp) [inline core/src/main/scala/pickling/Macros.scala:195]: weird line break inserted here after }

File: core/src/main/scala/pickling/Macros.scala [hunk 2]
```diff
@@ -225,11 +229,16 @@ trait PicklerMacros extends Macro with PickleMacros with FastTypeTagMacros {
           else reflectively("picklee", fir)(fm => putField(q"$fm.get.asInstanceOf[${fir.tpe}]"))
         } else if (fir.javaSetter.isDefined) {
           List(putField(getField(fir)))
-        } else {
+        } else if (fir.isParam) {
           reflectivelyWithoutGetter("picklee", fir)(fvalue =>
             tryPutField(q"$fvalue.asInstanceOf[scala.util.Try[${fir.tpe}]]"))
+        } else {
+          Nil
```
Comment (havocp) [inline core/src/main/scala/pickling/Macros.scala]: what does this case mean exactly, that we found a field but don't know how to pickle it? If so should the error be here (if we're losing _any_ field it's an error) rather than below (if we lose _all_ the fields)?

File: core/src/main/scala/pickling/Macros.scala [hunk 3]
```diff
@@ -225,11 +229,16 @@ trait PicklerMacros extends Macro with PickleMacros with FastTypeTagMacros {
...
         }
       })
+      if (cir.fields.nonEmpty && putFields.isEmpty) {
+        throw PicklingException("No fields are captured. You need a custom pickler to handle this.")
+      }
```
Comment (havocp) [inline core/src/main/scala/pickling/Macros.scala:241]: this doesn't seem clear enough to me. It could be something like `"fields $fieldNames are needed to construct $typeName, but pickling's generate macro didn't find a getter for these fields, so you will have to write a custom pickler"` ? I'm not sure I understand exactly why this happens though - if we found the field, why can't we use reflection to get it? Anyway whatever the surrounding explanation it's important to include the field and type names.

File: core/src/test/scala/pickling/neg/java-field-fail.scala [hunk 4]
```diff
@@ -0,0 +1,20 @@
+package scala.pickling.javafieldfail
+
+import scala.pickling._
+import NegativeCompilation._
+import org.scalatest.FunSuite
+
+class JavaFieldFailTest extends FunSuite {
+  test("main") {
+    expectError("Cannot generate") {
```
Comment (havocp) [inline core/src/test/scala/pickling/neg/java-field-fail.scala:9]: this is the `implicitNotFound` error right - it might be better to try to compile an explicit `Pickler.generate[java.lang.Byte]` and check for the specific PicklingException you added ?

File: core/src/main/scala/pickling/Macros.scala (hunk 1 above)
Comment (eed3si9n) [inline core/src/main/scala/pickling/Macros.scala:195]: The entire else clause is indented incorrectly, but fixing that was going to make the PR harder to review so I undid the change. I'll fix indentation afterwards.

File: core/src/main/scala/pickling/Macros.scala (hunk 2 above)
Comment (eed3si9n) [inline core/src/main/scala/pickling/Macros.scala]: There may be discrepancies between pure Java and Scala behavior, but "fields" from IR includes parameters to the primary constructor since they do turn into a field sometimes.
The following is using 0.10.x:

``` scala
scala> class Foo(x0: Int) { val x = x0 }
defined class Foo

scala> new Foo(1).pickle
res0: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "Foo",
  "x": 1
})

scala> class Bar(x0: Int) { val x = x0; override def toString = x0.toString }
defined class Bar

scala> new Bar(1).pickle
res1: scala.pickling.json.pickleFormat.PickleType =
JSONPickle({
  "$type": "Bar",
  "x": 1,
  "x0": 1
})
```

My change would no longer attempt to capture `x0`. It's currently using weird try-catch-em-all, and I figured that's the source of the problem. I think I need to check if the given type is pure Java or not.

Comment (havocp) [inline core/src/main/scala/pickling/Macros.scala]: Characterize the difference in Foo and Bar for me in that example? Is it that the reference in Bar.toString causes the scala compiler to generate a field for x0 and in Foo it  doesn't generate a field?

The code looks to me like currently for a field it always tries to generate a putField, but with your change it only tries to generate getField if the field `isParam` (which means it's a constructor parameter it looks like). But that doesn't seem to match what you're saying about `x0` in the example? what am I missing?

Comment (eed3si9n) [inline core/src/main/scala/pickling/Macros.scala]: > Characterize the difference in Foo and Bar for me in that example? Is it that the reference in Bar.toString causes the scala compiler to generate a field for x0 and in Foo it doesn't generate a field?

I think so.

> But that doesn't seem to match what you're saying about x0 in the example? what am I missing?

The REPL example I posted is from 0.10.x branch. This PR would likely break `Bar` example, but it also prevents `java.lang.Byte` from generating an empty object. I need more code so it works for both cases.

File: core/src/main/scala/pickling/Macros.scala (hunk 3 above)
Comment (eed3si9n) [inline core/src/main/scala/pickling/Macros.scala:241]: This happens because `IRs` picks up all sorts weird things as "fields" as fields, including the parameters to the primary constructor. And to cover it up, `reflectivelyWithoutGetter` does try-catch-NoSuchFieldException-ignore.

File: core/src/test/scala/pickling/neg/java-field-fail.scala (hunk 4 above)
Comment (eed3si9n) [inline core/src/test/scala/pickling/neg/java-field-fail.scala:9]: REPL gives me what we want, 

```
scala> Pickler.generate[FakeByte]
<console>:18: error: exception during macro expansion:
scala.pickling.PicklingException: No fields are captured. You need a custom pickler to handle this.
    at scala.pickling.PicklerMacros$$anonfun$pickleLogic$1.unifiedPickle$1(Macros.scala:240)
```

but I get an error that I don't want using the negative test:

```
[info] macro implementation not found: generate
[info] (the most common reason for that is that you cannot use macro implementations in the same compilation run that defines them)
```

so I am guessing it's specific to Toolbox used by negative test.

**Comment by phaller** [comment]
LGTM

**Comment by jsuereth** [comment]
LGTM

File: core/src/main/scala/pickling/Macros.scala [hunk 5]
```diff
@@ -225,11 +229,16 @@ trait PicklerMacros extends Macro with PickleMacros with FastTypeTagMacros {
...
           List(putField(getField(fir)))
+        } else if (!fir.isParam && sym.isJava) {
+          Nil
         } else {
           reflectivelyWithoutGetter("picklee", fir)(fvalue =>
             tryPutField(q"$fvalue.asInstanceOf[scala.util.Try[${fir.tpe}]]"))
         }
       })
+      if (cir.fields.nonEmpty && putFields.isEmpty) {
+        throw PicklingException("No fields are captured. You need a custom pickler to handle this.")
```
Comment (jsuereth) [inline core/src/main/scala/pickling/Macros.scala:240]: I think here, because you're targeting 0.10.x, you should mention how if this code previously compiled, then the genreated pickler was inaccurate and should not be trusted.
